apiVersion: 0.3.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://YOUR-CLUSTER-IP-ADDRESS:6443
    k8sVersion: v1.12.2
    path: default
kind: ksonnet.io/app
libraries:
  kubeflow/tf-serving:
    name: tf-serving
    registry: kubeflow
    version: ""
name: object-detection-app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
